// generated by stringer -type=TokenType; DO NOT EDIT

package down

import "fmt"

const _TokenType_name = "HeaderSixTypeHeaderOneTypeHeaderTwoTypeTextTypeHeaderEndType"

var _TokenType_index = [...]uint8{0, 13, 26, 39, 47, 60}

func (i TokenType) String() string {
	if i < 0 || i+1 >= TokenType(len(_TokenType_index)) {
		return fmt.Sprintf("TokenType(%d)", i)
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
